version: '3.3'
services:
  frontend:
    build: frontend
    ports:
      - '4200:4200'
    volumes:
      - './frontend:/app'
      - /app/node_modules
    command: ng serve
  frontend_node_modules:
    build: frontend
    ports:
      - '4200:4200'
    volumes:
      - './frontend:/app'
    command: npm install
