version: '3.8'

services:
    frontend:
        build: frontend
        ports:
            - 4200:4200
        volumes: 
            - ./frontend:/app
            - /app/node_modules
        command: ng serve

    #this will update the node modules folder in the frontend directory
    frontend_node_modules:
        build: frontend
        ports:
            - 4200:4200
        volumes: 
            - ./frontend:/app
        command: npm install